version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    container_name: rest_shop
    restart: unless-stopped
    environment:
      POSTGRES_DB: rest_shop
      POSTGRES_USER: rest_shop
      POSTGRES_PASSWORD: rest_shop
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
